name: tiny-redis
on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
    - 'Cargo.toml'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'
    - 'Cargo.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
